config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  
  devise_for :users , controllers: { registrations: 'registrate' }


  resources :projects do 
    resources :developerbugs 
    resources :developerprojects
    resources :developers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
    belongs_to :project

    has_many :developerbugs , foreign_key: :user_id
    has_many :developers, class_name: "User", foreign_key: "user_id", dependent: :destroy ,through: :developerbugs

    validates :title , presence: true ,length: { in: 5..30 } , uniqueness: true
    validates :description, presence: true ,length: { in: 5..150 }
    validates :type, presence: true, inclusion: ["Feature", "Bug"]
    validates :status, presence: true, inclusion: ["new", "started", "completed"]

    self.inheritance_column = :_type_disabled

    after_initialize :init


    def init
        self.status  ||= "new"
    end
end 

app/models/developer.rb
class Developer < User
    has_many :developerprojects, foreign_key: :user_id
    has_many :projects, dependent: :destroy, through: :developerprojects

    has_many :developerbugs , foreign_key: :user_id
    has_many :bugs, dependent: :destroy, through: :developerbugs
end

app/models/developerbug.rb
class Developerbug < ApplicationRecord 
    belongs_to :developer, class_name: "User", foreign_key: "user_id"
    belongs_to :bug

end

app/models/developerproject.rb
class Developerproject < ApplicationRecord
    belongs_to :developer, class_name: "User", foreign_key: "user_id"
    belongs_to :project
end

app/models/manager.rb
class Manager < User
    has_many :projects, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :manager, class_name: "User", foreign_key: "user_id"
    has_many :bugs , dependent: :destroy
    has_many :developerprojects , foreign_key: :user_id
    has_many :developers, class_name: "User", foreign_key: "user_id", dependent: :destroy, through: :developerprojects



  validates :name , presence: true ,length: { in: 5..30 }
  validates :description, presence: true ,length: { in: 5..300 }
end  

app/models/qa.rb
class Qa < User
    has_many :bugs , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name , presence: true ,length: { in: 2..20 }
  validates :email, presence: true
  validates :password, presence: true ,length: { in: 3..10 }  ,format: { with: /[A-Za-z]{3}/, message: "Three characters are compulsory" }
  validates :type, presence: true, inclusion: ["Manager", "Developer", "Qa"]

  after_create :wellcome_email

  private

    def wellcome_email
      WellcomeMailer.wellcome_our_website(self).deliver_later
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery

    before_action :authenticate_user!
end

app/controllers/developerbugs_controller.rb
class DeveloperbugsController < ApplicationController 
    def index 
        @project = Project.find(params[:project_id])
        @developerbugs = Developerbug.joins(:bug).where(:bug=>{project_id: @project.id})
    end

    def show 
        @developerbug = Developerbug.find(params[:id])
    end

    def new 
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.new
    end

    def create 
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.create(title: params[:bug][:title], description: params[:bug][:description], type: params[:bug][:type] , user_id: current_user.id)
        if @bug 
            @bug.save 
        end 

        @developerbug = Developerbug.create(user_id: current_user.id , bug_id: @bug.id)
             
        if @developerbug.save 
            redirect_to project_developerbugs_path
        end
       
    end

    def edit 
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.new
    end

    def update 
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.find(params[:id])
        
        @bugg= @bug.update(title: @bug.title , description: @bug.description, type: @bug.type , status:params[:bug][:status] )
        if(@bugg)
            redirect_to project_developerbugs_path
        end    
    end


    def destroy 
        @projectbug = authorize Developerbug.find_by(bug_id: params[:developerbug][:bug_id] , user_id: params[:id])
        if @projectbug.destroy 
            redirect_to project_developerbugs_path 
        else 
            render "index" 
        end 
    end

end 

app/controllers/developerprojects_controller.rb
class DeveloperprojectsController < ApplicationController
    def index 
        @project = Project.find(params[:project_id])
        @developers = Developerproject.all.where(project_id: @project.id)
    end

    def destroy 
        @developer = Developerproject.find_by(user_id: params[:id] , project_id: params[:project_id] )
        if @developer.destroy 
            redirect_to root_path 
        else 
            render "index"
        end 
    end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
    def index
        @project = Project.find(params[:project_id])
        @developers = Developer.left_outer_joins(:developerprojects).where(:developerprojects=>{:user_id => nil})
    end

    def create

        @developerproject = Developerproject.new(project_id: params[:project_id],user_id: params[:developer][:user_id])
        if @developerproject
            @developerproject.save 
        end

    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index 
        @projects = policy_scope(Project)
    end 

    def show
        @project = Project.find(params[:id])
    end

    def new 
        @project = authorize Project.new
    end

    def create 
        @project = Project.new(project_params)
        @project.user_id = current_user.id

        if @project.save 
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
        @project = authorize Project.find(params[:id])
    end

    def update 
        @project = Project.find(params[:id])
        if @project.update(project_params)
            redirect_to root_path
        else
            render 'edit'
        end
    end

    def destroy
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to root_path
    end
    
private
    def project_params 
        params.require(:project).permit(:name, :description);
    end
end

app/controllers/registrate_controller.rb
class RegistrateController < Devise::RegistrationsController 
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrate_helper.rb
module RegistrateHelper
end

app/views/developerbugs/edit.html.erb
<% content_for :title, "Edit" %>
<% content_for :page_title, "Update Bug or feature status" %>

<% @bug.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger container"><%= msg %></div>
<% end %>

<%= form_with(model: @bug , url: project_developerbug_path , method: :patch) do |form| %>
<div class="container my-5">
    <div class="form-group">
        <label for="postname">Enter Status</label><br />
        <%= form.select :status, [:new, :started, :completed], {}, {class: "form-control"} %></br>
    </div>
    <div class="text-center">
        <%= form.submit "Update", class: "btn btn-secondary"%>
    </div>
<% end %>

app/views/developerbugs/index.html.erb
<% content_for :title, "Bugs & Features" %>
<% content_for :page_title, "Bugs And Features" %>

<div class="container my-3 overflow-x">
    <table class="table">
        <thead>
            <tr class="pl-3">
                <th scope="col">Bug Title</th>
                <th scope="col">Bug Type</th>
                <th scope="col">Bug Status</th>
                <th scope="col">Bug Detail</th>
                <% if policy(:Developerbug).edit? %>
                    <th scope="col">Update Status</th>
                <% end %>
                <% if policy(:Developerbug).destroy? %>
                    <th scope="col">Delete Bug</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @developerbugs.each do |b| %>
            <tr>
                <td><%= b.bug.title %></td>
                <td><%= b.bug.type %></td>
                <td><%= b.bug.status %></td>
                <td><%= link_to "Bug detail", project_developerbug_path(@project, b), class:"btn" %></td>
                <% if current_user.type == "Developer" %>
                    <td> 
                        <%= link_to "Update Status", edit_project_developerbug_path(@project, b), class:"btn btn-secondary" %>
                    </td>
                <% end %>
                <% if current_user.type == "Manager" %>
                    <td> 
                        <%= form_with(model: b, url: project_developerbug_path(@project,b.user_id ), method: :delete) do |form| %>
                            <%= form.hidden_field :bug_id, value: b.bug_id %>
                            <%= form.submit "Delete Bug", class: "btn btn-danger"%>
                        <% end %>
                    </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div> 

app/views/developerbugs/new.html.erb
<% content_for :title, "Create" %>
<% content_for :page_title, "Create Bug or feature on project" %>


<% @bug.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger container"><%= msg %></div>
<% end %>

<%= form_with(model: @bug , url: project_developerbugs_path , method: :post) do |form| %>
<div class="container my-5">
    <div class="form-group">
        <label for="title">Enter Name</label><br />
        <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <label for="postname">Enter Type</label><br />
        <%= form.select :type,[:Feature, :Bug] ,{}, {class: "form-control"} %></br>
    </div>
    <div class="form-group">
        <label for="postname">Enter Description</label><br />
        <%= form.text_area :description, class: "form-control project_text_area" %></br>
    </div>

    <div class="text-center">
        <%= form.submit "Add", class: "btn btn-secondary"%>
    </div>
<% end %>

app/views/developerbugs/show.html.erb
<% content_for :title, "Bug & Feature" %>
<% content_for :page_title, "Bug Or Feature Detail" %>

<div class="container my-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h3><strong>Created By : </strong><%= @developerbug.developer.name %></h3>
            <h3 class="text-center"><strong>Title : </strong><%= @developerbug.bug.title %></h2>
            <p class="lead"><%= @developerbug.bug.description %></p>
        </div>
    </div>
</div>

app/views/developerprojects/index.html.erb
<% content_for :title, "Working Employees" %>
<% content_for :page_title, "Developer Working On Project" %>

<div class="container my-3 overflow-x">
    <table class="table">
        <thead> 
            <tr class="pl-3">
                <th scope="col">Project Name</th>
                <th scope="col">Assign Project</th>
            </tr>
        </thead>
        <tbody>
            <% @developers.each do |dev| %>
            <tr>
                <td><%= dev.developer.name %></td>
                <td>
                    <%= link_to "Remove", project_developerproject_path(@project,dev.user_id), method: :delete %>
                </td>
            </tr>

            <% end %>
        </tbody>
    </table>
</div> 

app/views/developers/index.html.erb
<% content_for :title, "Assign Developer" %>
<% content_for :page_title, "Assign Developer" %>

<div class="container my-3 overflow-x">
    <table class="table">
        <thead> 
            <tr class="pl-3">
                <th scope="col">Project Name</th>
                <th scope="col">Assign Project</th>
            </tr>
        </thead>
        <tbody>
            <% @developers.each do |dev| %>
            <tr>
                <td><%= dev.name %></td>
                <td>
                    <%= form_with(model: dev, url: project_developers_path, method: :post) do |form| %>
                        <%= form.hidden_field :user_id, value: dev.id %>
                        <%= form.submit "Assign", class: "btn btn-secondary"%>
                    <% end %>
                </td>
            </tr>

            <% end %>
        </tbody>
    </table>
</div> 

app/views/layouts/_details.html.erb
<header class="bg-primary text-white">
    <div class="container text-center pt-5 pb-5">
      <h1><%= yield :page_title %> </h1>
    </div>
</header>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to "Pro Dev", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <% if policy(:project).new? %>
                <li class="nav-item active">
                    <%= link_to "Create Project", new_project_path, class: "nav-link" %>
                </li>
                <% end %>
                <li class="nav-item">
                    <%= link_to "Logout" , destroy_user_session_path, method: :delete, class: "nav-link"%>
                </li>
            </ul>
        </div>
        <div class="ml-auto">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to current_user.name , destroy_user_session_path, method: :delete, class: "nav-link"%>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    
   <% if user_signed_in? %>
      <%= render "layouts/navigation" %>
      <%= render "layouts/details" %>
    <% end %>

    <%= yield %> 
  </body>
</html> 

app/views/managers/new.html.erb
<% content_for :title, "Create" %>
<%= render "projects/new" %>

app/views/projects/_form.html.erb
<%= form_with model: project  do |form| %>
<div class="container my-5">
    <div class="form-group">
        <label for="title">Enter Name</label><br />
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <label for="postname">Enter Description</label><br />
        <%= form.text_area :description, class: "form-control project_text_area" %></br>
    </div>
    <div class="text-center">
        <%= form.submit project.persisted? ? "Updata Project" : "Add Project", class: "btn btn-secondary"%>
    </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Edit" %>
<% content_for :page_title, "Edit" %>

<% @project.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger container"><%= msg %></div>
<% end %>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<% content_for :title, "Home" %>
<% content_for :page_title, "Projects" %>

<div class="container my-3 overflow-x">
    <table class="table">
        <thead>
            <tr class="pl-3"> 
                <th scope="col">Project Name</th>
                <th scope="col">Project Detail</th>
                <% if policy(:project).edit? %>
                <th scope="col">Assign Developer</th>
                <th scope="col">Working Developer</th>
                <th scope="col">Edit</th>
                <% end %>
                <% if policy(:project).destroy? %>
                <th scope="col">Delete</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @projects.each do |p| %>
            <tr>
                <% if p != nil %>
                <td><%= p.name %></td>
                <td><%= link_to "See Detail", project_path(p) , class: "btn"%></td>
                <% if policy(:project).edit? %>
                <td><%= link_to "Assign developer", project_developers_path(p), class: "btn"%></td>
                <td><%= link_to "Working developer", project_developerprojects_path(p), class: "btn" %></td>
                <td><%= link_to "Edit", edit_project_path(p), class: "btn btn-secondary" %></td>
                <% end %>
                <% if policy(:project).destroy? %>
                <td><%= link_to "Delete", project_path(p) , method: :delete, class: "btn btn-danger" %></td>
                <% end %>

                <% else %>
                <td colspan="3"> No Found Any Project </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

 

app/views/projects/new.html.erb
<% content_for :title, "Create" %>
<% content_for :page_title, "Create Your Project" %>

<% @project.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger container"><%= msg %></div>
<% end %>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<% content_for :title, "Project Detail" %>
<% content_for :page_title, "Project Detail" %>


<div class="container my-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h2 class="text-center"><%= @project.name %></h2>
            <p class="lead"><%= @project.description %></p>
            <div class="text-center mt-5">
            <%= link_to "Create Bug or feature", new_project_developerbug_path( @project), class: "btn btn-success mt-3" %>
            <%= link_to "See Bugs and Feature", project_developerbugs_path( @project) , class: "btn btn-secondary mt-3" %>
        </div>
        </div>
    </div>
</div>